- hosts: all
  tasks:
    - name: install prerequisites
      apt:
        pkg:
          - build-essential
          - git
          - unzip
          - zip
          - nload
          - tree
    - name: install nginx
      apt: name=nginx state=latest
    - name: install python
      apt: 
        pkg:
        - python3-pip
        - python3-dev
        - python3-venv
    - name: install uwsgi dependencies
      install_recommends: no
      apt:
        pkg:
        - libpcre3-dev
        - libz-dev
    - name: install fail2ban
      apt: name=fail2ban state=latest
    - name: allow access to port 22
      ufw:
        rule: allow
        port: '22'
    - name: allow access to port 80
      ufw:
        rule: allow
        port: '80'
    - name: allow access to port 443
      ufw:
        rule: allow
        port: '443'
    - name: enable firewall
      ufw:
        state: enabled
    - name: create code directory
      file:
        path: /apps/logs/flask_tasks/app_log
        state: directory
        mode: 0775
        recurse: true
    - name: top level directory is 777 mode
      file:
        path: /apps
        state: directory
        mode: 0777
    - name: clone git repo
      git:
        repo: https://github.com/oliveryh/flask-tasks
        dest: /apps/app_repo
        version: develop
        force: yes
    - name: upgrade pip
      pip:
        virtualenv: /apps/venv
        virtualenv_command: /usr/bin/python3 -m venv
        name:
          - pip
          - setuptools
          - httpie
          - glances
          - uwsgi
    - name: install pip requirements
      pip:
        virtualenv: /apps/venv
        requirements: /apps/app_repo/requirements.txt
    - name: copy service file
      copy:
        src: ./flask_tasks.service
        dest: /etc/systemd/system/flask_tasks.service
    - name: start flask_tasks service
      service:
        name: flask_tasks
        state: started
    - name: remove standard nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: add flask_tasks nginx config
      copy:
        src: ./flask_tasks.nginx
        dest: /etc/nginx/sites-enabled/flask_tasks.nginx
    - name: update nginx
      shell:
        cmd: update-rc.d nginx enable
    - name: restart nginx
      service:
        name: nginx
        state: restarted